user authentication
harerajo/node-practice pull request #5
Opened 2022-03-11 09:04 UTC by harerajo

#### What does this PR do?

- Implements CRUD operations for blogs

#### Description of Task to be completed? 

- User should be able to create, update, comment on, delete, read a list of articles
#### How should this be manually tested?

- using postman, go to `localhost/5000/api`
- `get` method on `/articles` to view list of articles
- `delete` method on `/articles/:id` to delete a certain article
- `put` method on `/articles/:id` to add changes to an article 
- `post` method on `/articles` to add a new item on the list
- `put` method on `/articles/:id/comment` to comment on the article

#### What are the relevant Pivotal Tracker/Trello stories?

- https://trello.com/c/fQ0iBQRf/21-view-a-list-of-their-articles
- https://trello.com/c/11UL2J1k
- https://trello.com/c/qxJSMjHz
- https://trello.com/c/7hckchjp
- https://trello.com/c/UHupCRz6

#### Screenshots (if appropriate)
-N/A

#### Questions:

- N/A

2022-03-12 17:01 UTC, PrinceNiyonshuti approved these changes
great work and large payload

2022-03-12 17:51 UTC, PatrickNiyogitare28 requested changes
Put `.env` file under `.gitignore` file. You don't need to push it to github

2022-03-12 17:53 UTC, PatrickNiyogitare28 commented on src/tests/e2e/auth.test.js
> +				console.log(res.body);
Remove `console.log`. Don't have to push it to prouction

2022-03-13 21:51 UTC, harerajo commented
> Put `.env` file under `.gitignore` file. You don't need to push it to github

is it allowed to push .env.example?

2022-03-14 17:45 UTC, shemalucien approved these changes
Good Work mn

2022-03-15 10:12 UTC, merged